<template>
  <div class="h-screen flex">
    <!-- Sidebar -->
    <Sidebar />
    
    <!-- Main Content -->
    <div class="flex-1 flex flex-col">
      <!-- Header -->
      <Header />
      
      <!-- Scripts Content -->
      <main class="flex-1 p-6">
        <div class="max-w-4xl mx-auto">
          <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-8">
            Script Generator
          </h1>
          
          <!-- Script Configuration -->
          <div class="card p-6 mb-6">
            <h2 class="text-xl font-semibold mb-4">Configuration</h2>
            
            <div class="grid grid-cols-2 gap-6">
              <div>
                <label class="block text-sm font-medium mb-2">Source Environment</label>
                <select class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700">
                  <option>DEV1</option>
                  <option>DEV2</option>
                  <option>STAGE</option>
                </select>
              </div>
              
              <div>
                <label class="block text-sm font-medium mb-2">Target Environment</label>
                <select class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700">
                  <option>STAGE</option>
                  <option>PROD</option>
                </select>
              </div>
              
              <div>
                <label class="block text-sm font-medium mb-2">Object Types</label>
                <div class="space-y-2">
                  <label class="flex items-center">
                    <input type="checkbox" checked class="mr-2" />
                    Tables
                  </label>
                  <label class="flex items-center">
                    <input type="checkbox" checked class="mr-2" />
                    Procedures
                  </label>
                  <label class="flex items-center">
                    <input type="checkbox" checked class="mr-2" />
                    Functions
                  </label>
                  <label class="flex items-center">
                    <input type="checkbox" class="mr-2" />
                    Triggers
                  </label>
                </div>
              </div>
              
              <div>
                <label class="block text-sm font-medium mb-2">Script Type</label>
                <select class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700">
                  <option>Export</option>
                  <option>Compare</option>
                  <option>Migration</option>
                </select>
              </div>
            </div>
          </div>
          
          <!-- Generated Script -->
          <div class="card p-6">
            <div class="flex items-center justify-between mb-4">
              <h2 class="text-xl font-semibold">Generated Script</h2>
              <div class="flex space-x-2">
                <button class="btn btn-secondary">Copy</button>
                <button class="btn btn-primary">Save</button>
              </div>
            </div>
            
            <pre class="bg-gray-50 dark:bg-gray-900 p-4 rounded-lg text-sm overflow-auto max-h-96"><code># Generated by andb-ui
# Date: {{ new Date().toLocaleString() }}

# Export script for DEV1 → STAGE
andb export -t tables -e DEV1
andb export -p procedures -e DEV1
andb export -f functions -e DEV1

# Compare script
andb compare -t tables -s DEV1 -d STAGE
andb compare -p procedures -s DEV1 -d STAGE
andb compare -f functions -s DEV1 -d STAGE

# Migration script
andb migrate:new -t tables -s DEV1 -d STAGE
andb migrate:new -p procedures -s DEV1 -d STAGE
andb migrate:new -f functions -s DEV1 -d STAGE</code></pre>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import Sidebar from '@/components/Sidebar.vue'
import Header from '@/components/Header.vue'
</script>
